# MATH 382 - Fall 2021
## Scientific Computing
Yashin Rodriguez
<hr>

# Lab Assignment \#2: Linear Algebra with Numpy

<hr>

## Goals:
<ul>
    <li>Familiarization with NumPy procedures to operate with matrices</li>
    <li>Construction and manipulation of matrices</li>
    <li>Implementation of basic matrix operations</li>
    <li>Handling Python Errors and Exceptions</li>
    <li>Recursive Functions</li>
</ul>

## Directions:

<ul>
    <li>Write your name above.</li>
    <li>Solve the following programming problems.</li>
    <li>Make sure your code includes a few lines to test its functionality.</li>
    <li>After completing all four problems, save your notebook as <tt>math382_LabAssign02_yx.ipynb</tt> (where <tt>x</tt> and <tt>y</tt> stand for your first and last names' initials), and upload your notebook to the assignment submission page.</li>
</ul>

## Useful Links:
<ul>
    <li><a href = "https://docs.python.org/3/tutorial/errors.html">Python 3 Errors and Exceptions</a></li>
    <li><a href = "https://rollbar.com/blog/throwing-exceptions-in-python/">Examples of Errors and Exceptions</a></li>    
</ul>

## <tt>import</tt> Packages Required for all Problems

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math

## Problem \#1. Tridiagonal Matrix

Write code to create a 2D <tt>NumPy</tt> array of size $n x n$ with 2's along the main diagonal, and -1's along the subdiagonals above and below the main diagonal. 

In [2]:
def tridiag(n):
    TD=np.eye(n)
    return 2*TD-np.diag(np.ones(n-1),k=1)-np.diag(np.ones(n-1),k=-1)
D = tridiag(9)
print('D = ',D)

D =  [[ 2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2.]]


## Problem \#2. Inner Product

Write a function <tt>InnerProd(x,y)</tt> that takes as input two 1D <tt>NumPy</tt> arrays $x$ and $y$, checks whether they are the same length, and returns either a message indicating that the dimensions don't agree, or the inner product of $x$ and $y$. Create two 1D <tt>NumPy</tt> arrays of the same length and test your code. Use <tt>NumPy</tt>'s <tt>.dot</tt> procedure to verify the functionality of your code.

In [3]:
def InnerProd(x,y): 
    m=x.shape[0]
    n=y.shape[0]
    assert(m==n), "x and y are not the same length"
    z=0.0
    for j in range(0,m):
        z += x[j]*y[j]
    return z
# code to test the function
x = np.array([1.,-1.0,4.0,0.3])
y = np.array([3.,1.0,-2.0,4.0])

np.dot(x,y)
    

-4.8

## Problem \#3. Matrix - Vector Product

Write a function <tt>MatVecProd(A,x)</tt> that takes as input the 2D <tt>NumPy</tt> array $A$ and the 1D <tt>NumPy</tt> array $x$, checks whether their product $Ax$ is defined, and returns either a message indicating the product is not defined, or the 1D array $y = Ax$. Create a 1D <tt>NumPy</tt> array of length $n = 12$ and mltiply it by the triagonal matrix created in Problem #1 to test your code. Use <tt>NumPy</tt>'s <tt>.dot</tt> procedure to verify the functionality of your code.

In [4]:
def MatVecProd(A,x):
    m, n = A.shape
    q = x.shape[0]
    
    assert(len(x.shape) == 1), "x is not one dimensional"
    assert(n == q), "A and x are not multiplicable"
    
    y = np.zeros(m, 'double')
    for j in range(0,n):
        y += x[j]*A[:,j]
    return y

# Code to test the function

A = 2.0*np.diag(np.ones(5, 'double'))
A -= np.diag(np.ones(4), k = 1) + np.diag(np.ones(4), k = -1)
x = np.ones(5, 'double')
print('x = ', x)

y = MatVecProd(A,x)
print('A = ', A)
print('y = ', y)
print(A.shape)
print(x.shape)
print(y.shape)

x =  [1. 1. 1. 1. 1.]
A =  [[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]
y =  [1. 0. 0. 0. 1.]
(5, 5)
(5,)
(5,)


## Problem \#4. Matrix - Matrix Product

Write a function <tt>MatrixProd(A,B)</tt> that takes as input two 2D <tt>NumPy</tt> arrays $A$ and $B$, checks whether their product $AB$ is defined, and returns either a message indicating the product is not defined, or the 2D array $C = AB$, where the $j^{th}$ column of $C$ is calculated as the Matrix - Vector product $AB_{:,j}$. Find the product of the following matrices:
<ol>
    <li type = "a"> The matrix from Problem #1 with $n = 8$ and its transpose.</li> 
    <li type = "a"> The matrix from Problem #1 with $n = 8$ and a rectangular matrix $B$ of size $m x 12$ that is multiplicable with the matrix from Problem #1 with $B_{i,i} = -1$, $B_{i, i \pm 1} = 1$, and $B_{i,j} = 0$ if $j \neq i -1, i, i+1$.</li>
</ol>
Use <tt>NumPy</tt>'s <tt>.dot</tt> procedure to verify the functionality of your code.

In [5]:
def MatrixProd(A,B):
    
    m, n = A.shape
    p, q = B.shape
    
    assert(n == p), "A and B are not multiplicable"
    
    C = np.zeros([m,q], 'double')
    for j in range(0,q):
        C[:,j] = MatVecProd(A,B[:,j])
    
    return C


In [6]:
#n=8 and its transpose 
A=TD8=tridiag(8)
B=print(TD8.T)
numpy.dot(A,B)

[[ 2. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  2.]]


NameError: name 'numpy' is not defined

## Problem \#5. Outer Product

Write a function <tt>OuterProd(x,y)</tt> that takes as input two 1D <tt>NumPy</tt> arrays $x$ and $y$, checks whether they are the same length, and returns either a message indicating that the dimensions don't agree, or the inner product of $x$ and $y$. Create two 1D <tt>NumPy</tt> arrays $x$ and $y$ of the same length and test your code. Use <tt>NumPy</tt>'s <tt>np.outer(x,y)</tt> procedure to verify the functionality of your code.

In [7]:
def OuterProd(x,y):
    m = x.shape[0]
    n = y.shape[0]
    
    assert(m == n), "x and y are not the same length" 
    
    XY = np.zeros([n,n],) 
    for j in range(0, n):
        XY[:,j] = y[j]*x
    
    return XY

# Code to test the function

x = np.array([2.0, 5.0, 7.0, 4.0, -5.0, 2.0])
y = np.array([2.0, 3.0, 1.0, 4.0, -5.0, 2.0])

XY = OuterProd(x,y)

print('XY = ', XY)
print(XY - np.outer(x,y))
        
        
        
        

XY =  [[  4.   6.   2.   8. -10.   4.]
 [ 10.  15.   5.  20. -25.  10.]
 [ 14.  21.   7.  28. -35.  14.]
 [  8.  12.   4.  16. -20.   8.]
 [-10. -15.  -5. -20.  25. -10.]
 [  4.   6.   2.   8. -10.   4.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Problem \#6. Determinants

Write a <b>recursive</b> function <tt>Determinant(A)</tt> that takes as input a 2D <tt>NumPy</tt> array $A$, checks whether it is a square array, and returns either a message indicating that the array isn't square, or the determinant of $A$. 
<ol>
    <li type = "a"> Find the determinant of the matrix in Problem #1 for $n = 2, 4, 8,$ and $10$. Use Python's <tt>time.time()</tt> function to find the $cpu$ time needed for each $n$. </li>
    <li type = "a"> How does the cpu time increase as $n$ increases?</li>
</ol>
Use <tt>NumPy</tt>'s <tt>np.linalg.det(A)</tt> procedure to verify the functionality of your code.

In [8]:
import time
def Determinant(A):
    m,n=A.shape
    # check it is a square matrix (use assert)
    #Base case n=2 (A is n x n)
    if n==2:
        return A[0,0]*A[1,1]-A[0,1]*A[1,0]

    else:#assume we use row 1(index=0)to calculate the determinant
       #Det(A)= sum((-1**(j)*A[0,j]*Determinant(M(0,j)),j=1...n-1)
       D=0.0
    for j in range(0,n): #list of number to n-1 assign j to the first number in the list
        M0j=np.zeros([n-1, n-1]) #rows 0 through n-2 of M0j corresonds to rows 1 through n-1 OF A
        M0j[0:n-1,0:j] = A[1:n,0:j]
        M0j[0:n-1,j:n-1] = A[1:n,j+1:n]
        D +=((-1.0)**j)*A[0,j]*Determinant(M0j)
    return D


In [9]:
#n=2
t_start=time.time()
TD2 = tridiag(2)
D = Determinant(TD2)
print('det(TD2) =',D, '\n')
print(D-np.linalg.det(TD2),'\n')
total_time = time.time() - t_start

print('time to compute 2x2 determiannt:', total_time, '\n')


det(TD2) = 3.0 

4.440892098500626e-16 

time to compute 2x2 determiannt: 0.0009140968322753906 



In [21]:
#n=4
t_start=time.time()
TD4 = tridiag(4)
D = Determinant(TD4)
print('det(TD4) =',D, '\n')
print(D-np.linalg.det(TD4),'\n')
total_time4 = time.time() - t_start

print('time to computer 4x4 determiannt:', total_time4, '\n')


det(TD4) = 5.0 

8.881784197001252e-16 

time to computer 4x4 determiannt: 0.0012280941009521484 



In [22]:
#n=8

t_start=time.time()
TD8 = tridiag(8)
D = Determinant(TD8)
print('det(TD8) =',D, '\n')
print(D-np.linalg.det(TD8),'\n')
total_time8 = time.time() - t_start

print('time to computer 8x8 determiannt:', total_time8, '\n')


det(TD8) = 9.0 

1.7763568394002505e-15 

time to computer 8x8 determiannt: 0.0758509635925293 



In [23]:
#n=10
t_start=time.time()
TD10= tridiag(10)
D = Determinant(TD10)
print('det(TD10) =',D, '\n')
print(D-np.linalg.det(TD10),'\n')
total_time10 = time.time() - t_start

print('time to computer 10x10 determiannt:', total_time10, '\n')


det(TD10) = 11.0 

3.552713678800501e-15 

time to computer 10x10 determiannt: 6.371206998825073 

